name: "HAFlow"
version: "0.1.2"
slug: "haflow"
description: "A flow editor and runner for Home Assistant automations."
url: "https://github.com/bptworld/haflow"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 4177
panel_icon: "mdi:vector-polyline"
homeassistant_api: true
options: {}
schema: {}
